name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Build for Linux
      run: dotnet publish -r linux-x64 --configuration Release /p:PublishSingleFile=true /p:PublishTrimmed=true
   
    - name: Build for Windows
      run: dotnet publish -r win-x64 --configuration Release /p:PublishSingleFile=true /p:PublishTrimmed=true
   
    - name: Upload artifact - Linux
      uses: actions/upload-artifact@v1.0.0
      with:
        name: WSE case study
        path: "WSE case study/bin/Release/netcoreapp3.1/linux-x64/publish/WSE case study"
    
    - name: Upload artifact - Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: WSE case study.exe
        path: "WSE case study/bin/Release/netcoreapp3.1/win-x64/publish/WSE case study.exe"
   
    - name: Make Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          "WSE case study/bin/Release/netcoreapp3.1/linux-x64/publish/WSE case study"
          "WSE case study/bin/Release/netcoreapp3.1/win-x64/publish/WSE case study.exe"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
